= Java client library for https://kafka.apache.org/documentation/#connect[Kafka Connect] REST Interface
:toc:
:toc-placement!:

image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[https://github.com/streamthoughts/kafka-connect-client/blob/master/LICENSE]
image:https://img.shields.io/github/v/release/streamthoughts/kafka-connect-client[GitHub release (latest by date)]
image:https://img.shields.io/github/issues-raw/streamthoughts/kafka-connect-client[GitHub issues]
image:https://img.shields.io/github/workflow/status/streamthoughts/kafka-connect-client/Java%20CI%20with%20Maven[GitHub Workflow Status]
image:https://img.shields.io/github/stars/streamthoughts/kafka-connect-client?style=social[GitHub Repo stars]

toc::[]

== Build the project

[source, bash]
----
./mvnw -B clean verify
----

== Code Examples

[source, java]
----
ApiClient client = Config.defaultClient();
Configuration.setDefaultApiClient(client);

ConnectRestClient client = new ConnectRestClient();

client.api().listConnectors();

----

== Licence

Copyright 2021 StreamThoughts.

Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0[http://www.apache.org/licenses/LICENSE-2.0]

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License

