/*
 * Copyright 2021 StreamThoughts.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.streamthoughts.kafka.connect.client.openapi.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** ConnectorInfo */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ConnectorInfo {
  public static final String SERIALIZED_NAME_NAME = "name";

  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CONFIG = "config";

  @SerializedName(SERIALIZED_NAME_CONFIG)
  private Map<String, String> config = new HashMap<>();

  public static final String SERIALIZED_NAME_TASKS = "tasks";

  @SerializedName(SERIALIZED_NAME_TASKS)
  private List<Task> tasks = new ArrayList<>();

  public ConnectorInfo name(String name) {

    this.name = name;
    return this;
  }

  /**
   * Name of the created connector
   *
   * @return name
   */
  @ApiModelProperty(required = true, value = "Name of the created connector")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ConnectorInfo config(Map<String, String> config) {

    this.config = config;
    return this;
  }

  public ConnectorInfo putConfigItem(String key, String configItem) {
    this.config.put(key, configItem);
    return this;
  }

  /**
   * Configuration parameters for the connector.
   *
   * @return config
   */
  @ApiModelProperty(required = true, value = "Configuration parameters for the connector.")
  public Map<String, String> getConfig() {
    return config;
  }

  public void setConfig(Map<String, String> config) {
    this.config = config;
  }

  public ConnectorInfo tasks(List<Task> tasks) {

    this.tasks = tasks;
    return this;
  }

  public ConnectorInfo addTasksItem(Task tasksItem) {
    this.tasks.add(tasksItem);
    return this;
  }

  /**
   * List of active tasks generated by the connector
   *
   * @return tasks
   */
  @ApiModelProperty(required = true, value = "List of active tasks generated by the connector")
  public List<Task> getTasks() {
    return tasks;
  }

  public void setTasks(List<Task> tasks) {
    this.tasks = tasks;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectorInfo connectorInfo = (ConnectorInfo) o;
    return Objects.equals(this.name, connectorInfo.name)
        && Objects.equals(this.config, connectorInfo.config)
        && Objects.equals(this.tasks, connectorInfo.tasks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, config, tasks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectorInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
